### Data Schema
<img src="https://i.imgur.com/HRhd2Y0.png" width="1000">

In [232]:
import pandas as pd

In [233]:
df_orders = pd.read_csv("./raw_data/olist_orders_dataset.csv")
df_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [234]:
df_orders = df_orders[df_orders['order_status'] == "delivered"]
df_orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

### Calculate Time to Deliver:
- time_to_delivery_from_shipment
- time_to_delivery_from_order_approved
- time_to_delivery_from_order_purchased

In [235]:
df_orders['order_delivered_carrier_date'] = df_orders['order_delivered_carrier_date'].astype('datetime64[ns]')
df_orders['order_delivered_customer_date'] = df_orders['order_delivered_customer_date'].astype('datetime64[ns]')
df_orders['order_approved_at'] = df_orders['order_approved_at'].astype('datetime64[ns]')
df_orders['order_purchase_timestamp'] = df_orders['order_purchase_timestamp'].astype('datetime64[ns]')
df_orders

C:\Users\victo\AppData\Local\Temp\ipykernel_12712\2193294280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['order_delivered_carrier_date'] = df_orders['order_delivered_carrier_date'].astype('datetime64[ns]')
C:\Users\victo\AppData\Local\Temp\ipykernel_12712\2193294280.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['order_delivered_customer_date'] = df_orders['order_delivered_customer_date'].astype('datetime64[ns]')
C:\Users\victo\AppData\Local\Temp\ipykernel_12712\2193294280.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['order_approved_at'] = df_orders['order_approved_at'].astype('datetime64[ns]')
C:\Users\victo\AppData\Local\Temp\ipykernel_12712\2193294280.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['order_purchase_timestamp'] = df_orders['order_purchase_timestamp'].astype('datetime64[ns]')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [236]:
def calculate_time_diff(df_start, df_end):
    return (df_end - df_start) / pd.Timedelta(days=1)

In [237]:
df_orders['time_to_delivery_from_shipment'] = calculate_time_diff(df_orders['order_delivered_carrier_date'], df_orders['order_delivered_customer_date'])
df_orders['time_to_delivery_from_order_approved'] = calculate_time_diff(df_orders['order_approved_at'], df_orders['order_delivered_customer_date'])
df_orders['time_to_delivery_from_order_purchased'] = calculate_time_diff(df_orders['order_purchase_timestamp'], df_orders['order_delivered_customer_date'])
df_orders

C:\Users\victo\AppData\Local\Temp\ipykernel_12712\4120122181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['time_to_delivery_from_shipment'] = calculate_time_diff(df_orders['order_delivered_carrier_date'], df_orders['order_delivered_customer_date'])
C:\Users\victo\AppData\Local\Temp\ipykernel_12712\4120122181.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['time_to_delivery_from_order_approved'] = calculate_time_diff(df_orders['order_approved_at'], df_orders['order_delivered_customer_date'])
C:\Users\victo\AppData\Local\Temp\ipykernel_12712\4120122181.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['time_to_delivery_from_order_purchased'] = calculate_time_diff(df_orders['order_purchase_timestamp'], df_orders['order_delivered_customer_date'])

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,6.062650,8.429144,8.436574
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,12.039410,12.502292,13.782037
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,9.178113,9.382708,9.394213
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,9.450498,13.196331,13.208750
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.937824,2.830938,2.873877
...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,7.159699,8.218009,8.218009
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,20.760579,22.185637,22.193727
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,23.605451,24.847234,24.859421
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,13.331840,17.080938,17.086424
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,6.622581,7.075023,7.674306

In [238]:
df_orders = df_orders.drop(
    columns=[
        'order_status', 
        #'order_purchase_timestamp', 
        'order_approved_at', 
        'order_delivered_carrier_date', 
        'order_delivered_customer_date', 
        'order_estimated_delivery_date'
    ]
)
df_orders.sort_values("order_purchase_timestamp", ascending=True, ignore_index=True)
df_orders

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,12.039410,12.502292,13.782037
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,9.178113,9.382708,9.394213
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,9.450498,13.196331,13.208750
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,1.937824,2.830938,2.873877
...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,2017-03-09 09:54:05,7.159699,8.218009,8.218009
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,2018-02-06 12:58:58,20.760579,22.185637,22.193727
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,2017-08-27 14:46:43,23.605451,24.847234,24.859421
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,13.331840,17.080938,17.086424
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,2018-03-08 20:57:30,6.622581,7.075023,7.674306

In [239]:
df_order_items = pd.read_csv("./raw_data/olist_order_items_dataset.csv")
df_seller = pd.read_csv("./raw_data/olist_sellers_dataset.csv")
df_geolocation = pd.read_csv("./raw_data/olist_geolocation_dataset.csv")
df_customers = pd.read_csv("./raw_data/olist_customers_dataset.csv")
df_products = pd.read_csv("./raw_data/olist_products_dataset.csv")

In [240]:
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [241]:
df_seller

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [242]:
df_geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [243]:
df_geolocation = df_geolocation.drop_duplicates(subset='geolocation_zip_code_prefix', keep="first", ignore_index=True)
df_geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1041,-23.544392,-46.639499,sao paulo,SP
3,1035,-23.541578,-46.641607,sao paulo,SP
4,1012,-23.547762,-46.635361,sÃ£o paulo,SP
...,...,...,...,...,...
19010,99955,-28.107588,-52.144019,vila langaro,RS
19011,99970,-28.345143,-51.876926,ciriaco,RS
19012,99910,-27.863500,-52.084760,floriano peixoto,RS
19013,99920,-27.858716,-52.300403,erebango,RS
19014,99952,-28.160371,-51.936922,santa cecilia do sul,RS

In [244]:
df_customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [245]:
df_seller['seller_id'].unique().shape

(3095,)

In [246]:
df_customers['customer_id'].unique().shape

(99441,)

In [247]:
df_order_merged = pd.merge(df_orders, df_order_items, on="order_id", how="inner")
df_order_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,12.039410,12.502292,13.782037,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,9.178113,9.382708,9.394213,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,9.450498,13.196331,13.208750,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,1.937824,2.830938,2.873877,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72
...,...,...,...,...,...,...,...,...,...,...,...,...
110192,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,2018-02-06 12:58:58,20.760579,22.185637,22.193727,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
110193,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,2017-08-27 14:46:43,23.605451,24.847234,24.859421,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
110194,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,13.331840,17.080938,17.086424,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
110195,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,2018-01-08 21:28:27,13.331840,17.080938,17.086424,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
110196,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,2018-03-08 20:57:30,6.622581,7.075023,7.674306,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [248]:
df_order_merged = pd.merge(df_order_merged, df_products, on="product_id", how="inner")
df_order_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-21 20:05:16,29.99,7.78,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,2017-08-02 18:24:47,3.037708,4.990810,5.003634,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-08 18:37:31,29.99,7.78,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,2017-10-23 23:26:46,11.052928,13.660278,14.776539,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-31 02:14:11,29.99,14.10,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
4,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,12.039410,12.502292,13.782037,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110192,e8fd20068b9f7e6ec07068bb7537f781,609b9fb8cad4fe0c7b376f77c8ab76ad,2017-08-10 21:21:07,4.953912,12.750729,12.760671,1,0df37da38a30a713453b03053d60d3f7,218d46b86c1881d022bce9c68a7d4b15,2017-08-17 21:35:26,356.00,18.12,esporte_lazer,53.0,1105.0,1.0,2800.0,28.0,23.0,23.0
110193,e8fd20068b9f7e6ec07068bb7537f781,609b9fb8cad4fe0c7b376f77c8ab76ad,2017-08-10 21:21:07,4.953912,12.750729,12.760671,2,0df37da38a30a713453b03053d60d3f7,218d46b86c1881d022bce9c68a7d4b15,2017-08-17 21:35:26,356.00,18.12,esporte_lazer,53.0,1105.0,1.0,2800.0,28.0,23.0,23.0
110194,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,2017-12-20 09:52:41,36.805428,37.232894,37.244826,1,3d2c44374ee42b3003a470f3e937a2ea,ce248b21cb2adc36282ede306b7660e5,2017-12-27 10:09:52,55.90,15.14,instrumentos_musicais,34.0,372.0,2.0,300.0,16.0,6.0,12.0
110195,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,2017-03-09 09:54:05,7.159699,8.218009,8.218009,1,ac35486adb7b02598c182c2ff2e05254,e24fc9fcd865784fb25705606fe3dfe7,2017-03-15 09:54:05,72.00,13.08,beleza_saude,50.0,1517.0,1.0,1175.0,22.0,13.0,18.0
110196,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,2018-03-08 20:57:30,6.622581,7.075023,7.674306,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

In [249]:
df_order_seller_merged = pd.merge(df_order_merged, df_seller, on="seller_id", how="inner")
df_order_seller_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,order_item_id,product_id,seller_id,shipping_limit_date,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-21 20:05:16,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,2017-08-02 18:24:47,3.037708,4.990810,5.003634,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-08 18:37:31,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,2017-10-23 23:26:46,11.052928,13.660278,14.776539,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-31 02:14:11,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,2017-08-10 13:35:55,5.215984,6.217674,6.227558,1,b00a32a0b42fd65efb58a5822009f629,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-16 13:50:09,...,58.0,398.0,3.0,238.0,20.0,10.0,15.0,9350,maua,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110192,1ab38815794efa43d269d62b98dae815,a0b67404d84a70ef420a7f99ad6b190a,2018-07-01 10:23:10,5.022882,3.950752,8.197072,1,31ec3a565e06de4bdf9d2a511b822b4d,babcc0ab201e4c60188427cae51a5b8b,2018-07-10 08:32:33,...,40.0,516.0,2.0,750.0,30.0,28.0,28.0,13660,porto ferreira,SP
110193,735dce2d574afe8eb87e80a3d6229c48,d531d01affc2c55769f6b9ed410d8d3c,2018-07-24 09:46:27,9.314988,9.474398,9.542454,1,1d187e8e7a30417fda31e85679d96f0f,d263fa444c1504a75cbca5cc465f592a,2018-07-30 11:24:27,...,43.0,729.0,2.0,2100.0,80.0,8.0,30.0,13478,americana,SP
110194,ba4ff7bab012df64eed239c402ba6a0d,48ebd9467fef647e9a0cd9c1b9bdbe24,2018-01-11 23:07:22,7.569155,18.497234,18.503067,1,dc2f80dfc6b4e57be59ec9dfe9140849,d6cd01c59123df02fc226eadbadb5f89,2018-01-17 23:15:46,...,43.0,1671.0,4.0,500.0,17.0,6.0,21.0,1207,sao paulo,SP
110195,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,2018-05-22 21:13:21,19.446863,21.066539,21.082037,1,6e1c2008dea1929b9b6c27fa01381e90,edf3fabebcc20f7463cc9c53da932ea8,2018-05-28 21:31:24,...,19.0,531.0,1.0,5900.0,41.0,21.0,41.0,8320,sao paulo,SP
110196,1565f22aa9452ff278638e87cc895678,56772dfbcbe7df908a284ff0d53adf7d,2018-05-15 17:41:00,4.883113,5.455694,5.868530,1,9c1e194db1d35a79d962ea610bfe0868,f3862c2188522d89860c38a3ea8b550d,2018-05-22 03:35:29,...,40.0,871.0,1.0,83.0,17.0,8.0,13.0,14092,ribeirao preto,SP

In [250]:
df_order_seller_geo_merged = pd.merge(
    df_order_seller_merged, #.rename(columns={"seller_zip_code_prefix": "zip_code"}), 
    df_geolocation, #.rename(columns={"geolocation_zip_code_prefix": "zip_code"}), 
    #on="zip_code",
    how="inner",
    left_on="seller_zip_code_prefix", right_on="geolocation_zip_code_prefix"
)
df_order_seller_geo_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,order_item_id,product_id,seller_id,shipping_limit_date,...,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,...,8.0,13.0,9350,maua,SP,9350,-23.680114,-46.452454,maua,SP
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-21 20:05:16,...,8.0,13.0,9350,maua,SP,9350,-23.680114,-46.452454,maua,SP
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,2017-08-02 18:24:47,3.037708,4.990810,5.003634,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-08 18:37:31,...,8.0,13.0,9350,maua,SP,9350,-23.680114,-46.452454,maua,SP
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,2017-10-23 23:26:46,11.052928,13.660278,14.776539,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-31 02:14:11,...,8.0,13.0,9350,maua,SP,9350,-23.680114,-46.452454,maua,SP
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,2017-08-10 13:35:55,5.215984,6.217674,6.227558,1,b00a32a0b42fd65efb58a5822009f629,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-16 13:50:09,...,10.0,15.0,9350,maua,SP,9350,-23.680114,-46.452454,maua,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109943,6c895a26a7b113a890c888e46f106907,55eaa25f13d0d25081e707fc622c64b1,2017-02-09 11:38:52,11.151748,33.192269,33.196898,1,210f0fc19063f1cbddd677a13d6e489f,bcd2d7510d58e293f20fad6438c1b314,2017-02-13 11:38:52,...,16.0,16.0,81540,curitiba,PR,81540,-25.464788,-49.220950,curitiba,PR
109944,a4e589b74835bc3afcbd2f9e8c5f7fd5,8b395f74a33054bc1e054c5b9348df51,2017-08-18 13:19:58,6.968993,10.552650,14.175139,1,2701fc4808fcb783d1347510b8b16698,7f02656561b680def9986c0795a8a080,2017-08-29 04:16:21,...,14.0,23.0,1417,sao paulo,SP,1417,-23.488510,-46.714606,sao paulo,SP
109945,a6c258c89be1621b6e7c2bd85b4c866d,669a87ed9830ed7d79b3a22210a1a52d,2018-04-26 08:13:16,11.355266,12.596435,12.609942,1,5a68d72870a735b2e7ec0277013f7aa6,b6f52e346160519c24a23af05410ad32,2018-05-03 08:31:17,...,11.0,11.0,1254,sao paulo,SP,1254,-23.541968,-46.681914,sÃ£o paulo,SP
109946,39e89b39b5cc8b5e3a38f23e915d1823,2b91bc260dcffbdacd12c4b09e5c7463,2017-07-24 11:29:43,16.880231,17.332512,17.341979,1,24fcd474105d95d2002f38f0cacf87ee,72c73be2b085b9d57650dd53eb2004c9,2017-07-28 11:43:21,...,7.0,11.0,2116,sao paulo,SP,2116,-23.522700,-46.587546,sao paulo,SP
109947,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,2018-05-22 21:13:21,19.446863,21.066539,21.082037,1,6e1c2008dea1929b9b6c27fa01381e90,edf3fabebcc20f7463cc9c53da932ea8,2018-05-28 21:31:24,...,21.0,41.0,8320,sao paulo,SP,8320,-23.635701,-46.462318,sao paulo,SP

In [251]:
df_order_seller_geo_customer_merged = pd.merge(
    df_order_seller_geo_merged, 
    df_customers, 
    on="customer_id", how="inner"
)
df_order_seller_geo_customer_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,order_item_id,product_id,seller_id,shipping_limit_date,...,seller_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,...,SP,9350,-23.680114,-46.452454,maua,SP,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-21 20:05:16,...,SP,9350,-23.680114,-46.452454,maua,SP,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,SP
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,2017-08-02 18:24:47,3.037708,4.990810,5.003634,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-08 18:37:31,...,SP,9350,-23.680114,-46.452454,maua,SP,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,SP
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,2017-10-23 23:26:46,11.052928,13.660278,14.776539,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-31 02:14:11,...,SP,9350,-23.680114,-46.452454,maua,SP,e781fdcc107d13d865fc7698711cc572,88032,florianopolis,SC
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,2017-08-10 13:35:55,5.215984,6.217674,6.227558,1,b00a32a0b42fd65efb58a5822009f629,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-16 13:50:09,...,SP,9350,-23.680114,-46.452454,maua,SP,02c9e0c05a817d4562ec0e8c90f29dba,8577,itaquaquecetuba,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109943,6c895a26a7b113a890c888e46f106907,55eaa25f13d0d25081e707fc622c64b1,2017-02-09 11:38:52,11.151748,33.192269,33.196898,1,210f0fc19063f1cbddd677a13d6e489f,bcd2d7510d58e293f20fad6438c1b314,2017-02-13 11:38:52,...,PR,81540,-25.464788,-49.220950,curitiba,PR,c74601008d7ec21da3155119b8ad7382,88780,imbituba,SC
109944,a4e589b74835bc3afcbd2f9e8c5f7fd5,8b395f74a33054bc1e054c5b9348df51,2017-08-18 13:19:58,6.968993,10.552650,14.175139,1,2701fc4808fcb783d1347510b8b16698,7f02656561b680def9986c0795a8a080,2017-08-29 04:16:21,...,SP,1417,-23.488510,-46.714606,sao paulo,SP,8b843efe35f8a54b66f7abf3e460e84d,14750,pitangueiras,SP
109945,a6c258c89be1621b6e7c2bd85b4c866d,669a87ed9830ed7d79b3a22210a1a52d,2018-04-26 08:13:16,11.355266,12.596435,12.609942,1,5a68d72870a735b2e7ec0277013f7aa6,b6f52e346160519c24a23af05410ad32,2018-05-03 08:31:17,...,SP,1254,-23.541968,-46.681914,sÃ£o paulo,SP,29eb806efe56d9cb4c9532edcc33ef15,13974,itapira,SP
109946,39e89b39b5cc8b5e3a38f23e915d1823,2b91bc260dcffbdacd12c4b09e5c7463,2017-07-24 11:29:43,16.880231,17.332512,17.341979,1,24fcd474105d95d2002f38f0cacf87ee,72c73be2b085b9d57650dd53eb2004c9,2017-07-28 11:43:21,...,SP,2116,-23.522700,-46.587546,sao paulo,SP,bd0a735ae91504c00c71638c720e3cca,45051,vitoria da conquista,BA
109947,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,2018-05-22 21:13:21,19.446863,21.066539,21.082037,1,6e1c2008dea1929b9b6c27fa01381e90,edf3fabebcc20f7463cc9c53da932ea8,2018-05-28 21:31:24,...,SP,8320,-23.635701,-46.462318,sao paulo,SP,e55e436481078787e32349cee9febf5e,39803,teofilo otoni,MG

In [252]:
df_order_seller_geo_customer_merged = df_order_seller_geo_customer_merged.drop(
    columns=[
        "seller_city", 
        "seller_state",
        "geolocation_city", 
        "geolocation_state", 
        "customer_unique_id", 
        "customer_city", 
        "customer_state", 
        "order_item_id", 
        #"product_id",
        "shipping_limit_date",
        #"zip_code",
        "seller_id",
        "product_category_name",
        "product_name_lenght",
        "product_description_lenght",
        "product_photos_qty"
    ]
)
df_order_seller_geo_customer_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,product_id,price,freight_value,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,customer_zip_code_prefix
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,87285b34884572647811a353c7ac498a,29.99,8.72,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,3149
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,87285b34884572647811a353c7ac498a,29.99,7.78,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,3366
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,2017-08-02 18:24:47,3.037708,4.990810,5.003634,87285b34884572647811a353c7ac498a,29.99,7.78,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,2290
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,2017-10-23 23:26:46,11.052928,13.660278,14.776539,87285b34884572647811a353c7ac498a,29.99,14.10,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,88032
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,2017-08-10 13:35:55,5.215984,6.217674,6.227558,b00a32a0b42fd65efb58a5822009f629,75.90,7.79,238.0,20.0,10.0,15.0,9350,9350,-23.680114,-46.452454,8577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109943,6c895a26a7b113a890c888e46f106907,55eaa25f13d0d25081e707fc622c64b1,2017-02-09 11:38:52,11.151748,33.192269,33.196898,210f0fc19063f1cbddd677a13d6e489f,23.90,15.56,600.0,80.0,16.0,16.0,81540,81540,-25.464788,-49.220950,88780
109944,a4e589b74835bc3afcbd2f9e8c5f7fd5,8b395f74a33054bc1e054c5b9348df51,2017-08-18 13:19:58,6.968993,10.552650,14.175139,2701fc4808fcb783d1347510b8b16698,42.00,11.85,1800.0,23.0,14.0,23.0,1417,1417,-23.488510,-46.714606,14750
109945,a6c258c89be1621b6e7c2bd85b4c866d,669a87ed9830ed7d79b3a22210a1a52d,2018-04-26 08:13:16,11.355266,12.596435,12.609942,5a68d72870a735b2e7ec0277013f7aa6,129.90,13.35,150.0,16.0,11.0,11.0,1254,1254,-23.541968,-46.681914,13974
109946,39e89b39b5cc8b5e3a38f23e915d1823,2b91bc260dcffbdacd12c4b09e5c7463,2017-07-24 11:29:43,16.880231,17.332512,17.341979,24fcd474105d95d2002f38f0cacf87ee,29.40,17.92,700.0,16.0,7.0,11.0,2116,2116,-23.522700,-46.587546,45051
109947,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,2018-05-22 21:13:21,19.446863,21.066539,21.082037,6e1c2008dea1929b9b6c27fa01381e90,219.90,24.12,5900.0,41.0,21.0,41.0,8320,8320,-23.635701,-46.462318,39803

In [253]:
df_order_seller_geo_customer_merged = df_order_seller_geo_customer_merged.rename(columns={"geolocation_lat": "seller_lat", "geolocation_lng": "seller_lng"})
df_order_seller_geo_customer_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,product_id,price,freight_value,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,geolocation_zip_code_prefix,seller_lat,seller_lng,customer_zip_code_prefix
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,87285b34884572647811a353c7ac498a,29.99,8.72,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,3149
1,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,87285b34884572647811a353c7ac498a,29.99,7.78,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,3366
2,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,2017-08-02 18:24:47,3.037708,4.990810,5.003634,87285b34884572647811a353c7ac498a,29.99,7.78,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,2290
3,bfc39df4f36c3693ff3b63fcbea9e90a,53904ddbea91e1e92b2b3f1d09a7af86,2017-10-23 23:26:46,11.052928,13.660278,14.776539,87285b34884572647811a353c7ac498a,29.99,14.10,500.0,19.0,8.0,13.0,9350,9350,-23.680114,-46.452454,88032
4,8736140c61ea584cb4250074756d8f3b,ab8844663ae049fda8baf15fc928f47f,2017-08-10 13:35:55,5.215984,6.217674,6.227558,b00a32a0b42fd65efb58a5822009f629,75.90,7.79,238.0,20.0,10.0,15.0,9350,9350,-23.680114,-46.452454,8577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109943,6c895a26a7b113a890c888e46f106907,55eaa25f13d0d25081e707fc622c64b1,2017-02-09 11:38:52,11.151748,33.192269,33.196898,210f0fc19063f1cbddd677a13d6e489f,23.90,15.56,600.0,80.0,16.0,16.0,81540,81540,-25.464788,-49.220950,88780
109944,a4e589b74835bc3afcbd2f9e8c5f7fd5,8b395f74a33054bc1e054c5b9348df51,2017-08-18 13:19:58,6.968993,10.552650,14.175139,2701fc4808fcb783d1347510b8b16698,42.00,11.85,1800.0,23.0,14.0,23.0,1417,1417,-23.488510,-46.714606,14750
109945,a6c258c89be1621b6e7c2bd85b4c866d,669a87ed9830ed7d79b3a22210a1a52d,2018-04-26 08:13:16,11.355266,12.596435,12.609942,5a68d72870a735b2e7ec0277013f7aa6,129.90,13.35,150.0,16.0,11.0,11.0,1254,1254,-23.541968,-46.681914,13974
109946,39e89b39b5cc8b5e3a38f23e915d1823,2b91bc260dcffbdacd12c4b09e5c7463,2017-07-24 11:29:43,16.880231,17.332512,17.341979,24fcd474105d95d2002f38f0cacf87ee,29.40,17.92,700.0,16.0,7.0,11.0,2116,2116,-23.522700,-46.587546,45051
109947,25d2bfa43663a23586afd12f15b542e7,9d8c06734fde9823ace11a4b5929b5a7,2018-05-22 21:13:21,19.446863,21.066539,21.082037,6e1c2008dea1929b9b6c27fa01381e90,219.90,24.12,5900.0,41.0,21.0,41.0,8320,8320,-23.635701,-46.462318,39803

In [254]:
df_order_seller_geo_customer_merged = pd.merge(
    df_order_seller_geo_customer_merged, #.rename(columns={"customer_zip_code_prefix": "zip_code"}), 
    df_geolocation, #.rename(columns={"geolocation_zip_code_prefix": "zip_code"}), 
    #on="zip_code",
    how="inner", left_on="customer_zip_code_prefix", right_on="geolocation_zip_code_prefix"
)
df_order_seller_geo_customer_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,product_id,price,freight_value,product_weight_g,...,seller_zip_code_prefix,geolocation_zip_code_prefix_x,seller_lat,seller_lng,customer_zip_code_prefix,geolocation_zip_code_prefix_y,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,87285b34884572647811a353c7ac498a,29.99,8.72,500.0,...,9350,9350,-23.680114,-46.452454,3149,3149,-23.574809,-46.587471,sao paulo,SP
1,70b35acffdf851e782ebf6fbc35eb620,8e8ee9b08afb49b080d193f98b0505af,2018-03-22 17:23:21,1.971968,2.970197,2.999537,6cc44821f36f3156c782da72dd634e47,99.90,11.79,1050.0,...,13405,13405,-22.716839,-47.657366,3149,3149,-23.574809,-46.587471,sao paulo,SP
2,70b35acffdf851e782ebf6fbc35eb620,8e8ee9b08afb49b080d193f98b0505af,2018-03-22 17:23:21,1.971968,2.970197,2.999537,6cc44821f36f3156c782da72dd634e47,99.90,11.79,1050.0,...,13405,13405,-22.716839,-47.657366,3149,3149,-23.574809,-46.587471,sao paulo,SP
3,69923a4e07ce446644394df37a710286,31f31efcb333fcbad2b1371c8cf0fa84,2017-09-04 11:26:38,0.915336,1.317303,1.328958,9abb00920aae319ef9eba674b7d2e6ff,35.39,8.72,350.0,...,7025,7025,-23.483785,-46.541554,3149,3149,-23.574809,-46.587471,sao paulo,SP
4,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,87285b34884572647811a353c7ac498a,29.99,7.78,500.0,...,9350,9350,-23.680114,-46.452454,3366,3366,-23.565578,-46.534603,sao paulo,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109656,b75ec2d4ba9e40634c65c4b6be946b6c,b84999d47cecf126835a23650ee4ecb8,2018-08-19 20:04:58,8.360694,9.183877,9.967662,73654d559ec8c7b46ae0c6419cd59072,579.00,19.15,300.0,...,1041,1041,-23.544392,-46.639499,70254,70254,-15.820763,-47.901087,brasilia,DF
109657,99a3d4b1228bc02abf9eec5d9a7a742d,0f71a0b83b78a05118efc4aae3c2a774,2018-07-17 21:05:10,7.117373,8.810197,8.817257,a2ead66678565eb7679dfdf1fa4cbe43,109.90,19.96,800.0,...,88340,88340,-27.032579,-48.658232,3050,3050,-23.542495,-46.613578,sao paulo,SP
109658,4442d1fdf454197e9e141f0d83a9031e,3c3c45651f50bb4b13a4de268cad02b0,2017-02-03 18:08:16,9.024213,25.182523,25.719780,7cb009e2ae1cdf7d16e8fbf0255ba953,1299.00,24.79,10800.0,...,7176,7176,-23.409499,-46.396566,97575,97575,-30.891886,-55.484419,santana do livramento,RS
109659,8fec1057df930bcc1be865fbfef606b4,1964a80794004a2f2456740630cc3b9d,2018-07-26 20:18:26,9.224028,12.487674,12.991782,0af2b3833420630d9d1eacc2daf2bdf9,230.00,28.56,1900.0,...,6340,6340,-23.565739,-46.823220,45750,45750,-14.894157,-39.428203,itape,BA
109660,5c533da06d7dfe10d9d44dbcc8bdbc6b,1285e7456591a89200ad22c4015c09ea,2017-07-02 13:10:36,19.217836,24.394572,24.404676,80d63636780c5975e5c93b63236d481d,142.47,43.41,2700.0,...,75345,75345,-16.766457,-49.434210,62051,62051,-3.673181,-40.369237,sobral,CE

In [255]:
df_order_seller_geo_customer_merged = df_order_seller_geo_customer_merged.drop(columns=["geolocation_state", "geolocation_city"])
df_order_seller_geo_customer_merged = df_order_seller_geo_customer_merged.rename(columns={"geolocation_lat": "customer_lat", "geolocation_lng": "customer_lng"})
df_order_seller_geo_customer_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,product_id,price,freight_value,product_weight_g,...,product_height_cm,product_width_cm,seller_zip_code_prefix,geolocation_zip_code_prefix_x,seller_lat,seller_lng,customer_zip_code_prefix,geolocation_zip_code_prefix_y,customer_lat,customer_lng
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,87285b34884572647811a353c7ac498a,29.99,8.72,500.0,...,8.0,13.0,9350,9350,-23.680114,-46.452454,3149,3149,-23.574809,-46.587471
1,70b35acffdf851e782ebf6fbc35eb620,8e8ee9b08afb49b080d193f98b0505af,2018-03-22 17:23:21,1.971968,2.970197,2.999537,6cc44821f36f3156c782da72dd634e47,99.90,11.79,1050.0,...,10.0,38.0,13405,13405,-22.716839,-47.657366,3149,3149,-23.574809,-46.587471
2,70b35acffdf851e782ebf6fbc35eb620,8e8ee9b08afb49b080d193f98b0505af,2018-03-22 17:23:21,1.971968,2.970197,2.999537,6cc44821f36f3156c782da72dd634e47,99.90,11.79,1050.0,...,10.0,38.0,13405,13405,-22.716839,-47.657366,3149,3149,-23.574809,-46.587471
3,69923a4e07ce446644394df37a710286,31f31efcb333fcbad2b1371c8cf0fa84,2017-09-04 11:26:38,0.915336,1.317303,1.328958,9abb00920aae319ef9eba674b7d2e6ff,35.39,8.72,350.0,...,14.0,12.0,7025,7025,-23.483785,-46.541554,3149,3149,-23.574809,-46.587471
4,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,87285b34884572647811a353c7ac498a,29.99,7.78,500.0,...,8.0,13.0,9350,9350,-23.680114,-46.452454,3366,3366,-23.565578,-46.534603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109656,b75ec2d4ba9e40634c65c4b6be946b6c,b84999d47cecf126835a23650ee4ecb8,2018-08-19 20:04:58,8.360694,9.183877,9.967662,73654d559ec8c7b46ae0c6419cd59072,579.00,19.15,300.0,...,18.0,18.0,1041,1041,-23.544392,-46.639499,70254,70254,-15.820763,-47.901087
109657,99a3d4b1228bc02abf9eec5d9a7a742d,0f71a0b83b78a05118efc4aae3c2a774,2018-07-17 21:05:10,7.117373,8.810197,8.817257,a2ead66678565eb7679dfdf1fa4cbe43,109.90,19.96,800.0,...,11.0,27.0,88340,88340,-27.032579,-48.658232,3050,3050,-23.542495,-46.613578
109658,4442d1fdf454197e9e141f0d83a9031e,3c3c45651f50bb4b13a4de268cad02b0,2017-02-03 18:08:16,9.024213,25.182523,25.719780,7cb009e2ae1cdf7d16e8fbf0255ba953,1299.00,24.79,10800.0,...,18.0,19.0,7176,7176,-23.409499,-46.396566,97575,97575,-30.891886,-55.484419
109659,8fec1057df930bcc1be865fbfef606b4,1964a80794004a2f2456740630cc3b9d,2018-07-26 20:18:26,9.224028,12.487674,12.991782,0af2b3833420630d9d1eacc2daf2bdf9,230.00,28.56,1900.0,...,21.0,21.0,6340,6340,-23.565739,-46.823220,45750,45750,-14.894157,-39.428203
109660,5c533da06d7dfe10d9d44dbcc8bdbc6b,1285e7456591a89200ad22c4015c09ea,2017-07-02 13:10:36,19.217836,24.394572,24.404676,80d63636780c5975e5c93b63236d481d,142.47,43.41,2700.0,...,24.0,16.0,75345,75345,-16.766457,-49.434210,62051,62051,-3.673181,-40.369237


### Calculate distance between seller and costumer
- How to do it!
```python
!pip install geopy

import geopy.distance

coords_1 = (52.2296756, 21.0122287)
coords_2 = (52.406374, 16.9251681)

print(geopy.distance.geodesic(coords_1, coords_2).km)
```

In [256]:
!pip install geopy

Requirement already satisfied: geopy in c:\users\victo\anaconda3\envs\ts_project\lib\site-packages (2.3.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\victo\anaconda3\envs\ts_project\lib\site-packages (from geopy) (2.0)

In [257]:
import geopy.distance

In [258]:
def calculate_distance_between_coords(lat1, lng1, lat2, lng2):
    coords_1 = (lat1, lng1)
    coords_2 = (lat2, lng2)

    return geopy.distance.geodesic(coords_1, coords_2).km

In [259]:
df_order_seller_geo_customer_merged["shipment_distance"] = df_order_seller_geo_customer_merged.apply(lambda row: calculate_distance_between_coords(row['customer_lat'], row['customer_lng'], row['seller_lat'], row['seller_lng']), axis=1)
df_order_seller_geo_customer_merged

,order_id,customer_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,product_id,price,freight_value,product_weight_g,...,product_width_cm,seller_zip_code_prefix,geolocation_zip_code_prefix_x,seller_lat,seller_lng,customer_zip_code_prefix,geolocation_zip_code_prefix_y,customer_lat,customer_lng,shipment_distance
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,6.062650,8.429144,8.436574,87285b34884572647811a353c7ac498a,29.99,8.72,500.0,...,13.0,9350,9350,-23.680114,-46.452454,3149,3149,-23.574809,-46.587471,18.051106
1,70b35acffdf851e782ebf6fbc35eb620,8e8ee9b08afb49b080d193f98b0505af,2018-03-22 17:23:21,1.971968,2.970197,2.999537,6cc44821f36f3156c782da72dd634e47,99.90,11.79,1050.0,...,38.0,13405,13405,-22.716839,-47.657366,3149,3149,-23.574809,-46.587471,145.028973
2,70b35acffdf851e782ebf6fbc35eb620,8e8ee9b08afb49b080d193f98b0505af,2018-03-22 17:23:21,1.971968,2.970197,2.999537,6cc44821f36f3156c782da72dd634e47,99.90,11.79,1050.0,...,38.0,13405,13405,-22.716839,-47.657366,3149,3149,-23.574809,-46.587471,145.028973
3,69923a4e07ce446644394df37a710286,31f31efcb333fcbad2b1371c8cf0fa84,2017-09-04 11:26:38,0.915336,1.317303,1.328958,9abb00920aae319ef9eba674b7d2e6ff,35.39,8.72,350.0,...,12.0,7025,7025,-23.483785,-46.541554,3149,3149,-23.574809,-46.587471,11.118201
4,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,2017-08-15 18:29:31,0.969560,2.777396,2.843889,87285b34884572647811a353c7ac498a,29.99,7.78,500.0,...,13.0,9350,9350,-23.680114,-46.452454,3366,3366,-23.565578,-46.534603,15.204950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109656,b75ec2d4ba9e40634c65c4b6be946b6c,b84999d47cecf126835a23650ee4ecb8,2018-08-19 20:04:58,8.360694,9.183877,9.967662,73654d559ec8c7b46ae0c6419cd59072,579.00,19.15,300.0,...,18.0,1041,1041,-23.544392,-46.639499,70254,70254,-15.820763,-47.901087,865.170022
109657,99a3d4b1228bc02abf9eec5d9a7a742d,0f71a0b83b78a05118efc4aae3c2a774,2018-07-17 21:05:10,7.117373,8.810197,8.817257,a2ead66678565eb7679dfdf1fa4cbe43,109.90,19.96,800.0,...,27.0,88340,88340,-27.032579,-48.658232,3050,3050,-23.542495,-46.613578,438.017601
109658,4442d1fdf454197e9e141f0d83a9031e,3c3c45651f50bb4b13a4de268cad02b0,2017-02-03 18:08:16,9.024213,25.182523,25.719780,7cb009e2ae1cdf7d16e8fbf0255ba953,1299.00,24.79,10800.0,...,19.0,7176,7176,-23.409499,-46.396566,97575,97575,-30.891886,-55.484419,1223.291635
109659,8fec1057df930bcc1be865fbfef606b4,1964a80794004a2f2456740630cc3b9d,2018-07-26 20:18:26,9.224028,12.487674,12.991782,0af2b3833420630d9d1eacc2daf2bdf9,230.00,28.56,1900.0,...,21.0,6340,6340,-23.565739,-46.823220,45750,45750,-14.894157,-39.428203,1234.654072
109660,5c533da06d7dfe10d9d44dbcc8bdbc6b,1285e7456591a89200ad22c4015c09ea,2017-07-02 13:10:36,19.217836,24.394572,24.404676,80d63636780c5975e5c93b63236d481d,142.47,43.41,2700.0,...,16.0,75345,75345,-16.766457,-49.434210,62051,62051,-3.673181,-40.369237,1754.780598

In [260]:
df_final = df_order_seller_geo_customer_merged.sort_values("order_purchase_timestamp", ascending=True, ignore_index=True)
df_final = df_final.drop_duplicates(ignore_index=True)
df_final = df_final.drop(columns=["customer_id", "seller_lat", "seller_lng", "customer_lat", "customer_lng"])
df_final

,order_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,product_id,price,freight_value,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,geolocation_zip_code_prefix_x,customer_zip_code_prefix,geolocation_zip_code_prefix_y,shipment_distance
0,bfbd0f9bdef84302105ad712db648a6c,2016-09-15 12:16:38,1.608160,54.813194,54.813194,5a6b04657a4c5ee34285d1e4619a96b4,44.99,2.83,1000.0,16.0,16.0,16.0,81810,81810,14600,14600,564.407287
1,3b697a20d9e427646d92567910af6d57,2016-10-03 09:44:50,3.000000,19.924525,23.178738,3ae08df6bcbfe23586dd431c40bddbb7,29.90,15.56,300.0,16.0,16.0,16.0,85801,85801,4106,4106,709.921605
2,be5bc2f0da14d8071e2d45451ad119d9,2016-10-03 16:56:50,6.073519,21.094375,24.057500,fd7fd78fd3cbc1b0a6370a7909c0a629,21.90,17.19,400.0,16.0,16.0,16.0,15802,15802,98280,98280,914.131568
3,a41c8759fbe7aab36ea07e038b2d4465,2016-10-03 21:13:36,8.958426,29.323819,30.572581,b72b39418216e944bb34e35f4d3ea8c7,36.49,17.24,767.0,26.0,8.0,20.0,18015,18015,90040,90040,816.498486
4,d207cc272675637bfed0062edffd0818,2016-10-03 22:06:03,9.863947,27.027488,27.542813,107177bf61755f05c604fe57e02467d6,119.90,13.56,2050.0,40.0,11.0,34.0,14940,14940,13185,13185,212.084845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99697,52018484704db3661b98ce838612b507,2018-08-29 12:25:59,1.382257,1.425810,1.432269,777798445efd625458a90c13f3b3e6e7,63.90,9.20,1500.0,28.0,22.0,18.0,5125,5125,5863,5863,18.854775
99698,0b223d92c27432930dfe407c6aea3041,2018-08-29 14:18:23,1.038831,1.079028,1.087870,2b4472df15512a2825ae86fd9ae79335,209.00,46.48,13550.0,48.0,49.0,49.0,82400,82400,80045,80045,10.343719
99699,168626408cb32af0ffaf76711caae1dc,2018-08-29 14:18:28,0.917720,1.098704,1.106979,bdcf6a834e8faa30dac3886c7a58e92e,45.90,15.39,1614.0,31.0,16.0,28.0,30111,30111,38600,38600,431.976676
99700,03ef5dedbe7492bdae72eec50764c43f,2018-08-29 14:52:00,0.858322,1.063623,1.072905,c7f27c5bef2338541c772b5776403e6a,24.90,8.33,450.0,28.0,9.0,19.0,1320,1320,9541,9541,10.312870
99701,35a972d7f8436f405b56e36add1a7140,2018-08-29 15:00:37,0.976806,1.050810,1.057627,d04857e7b4b708ee8b8b9921163edba3,84.99,8.76,450.0,16.0,4.0,20.0,4102,4102,13483,13483,140.915746

In [261]:
duplicated_ids = df_final[df_final["order_id"].isin(df_final["order_id"][df_final["order_id"].duplicated()])].sort_values("order_id")
df_final = df_final[~df_final['order_id'].isin(duplicated_ids["order_id"].values.tolist())]
df_final

,order_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,product_id,price,freight_value,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,geolocation_zip_code_prefix_x,customer_zip_code_prefix,geolocation_zip_code_prefix_y,shipment_distance
0,bfbd0f9bdef84302105ad712db648a6c,2016-09-15 12:16:38,1.608160,54.813194,54.813194,5a6b04657a4c5ee34285d1e4619a96b4,44.99,2.83,1000.0,16.0,16.0,16.0,81810,81810,14600,14600,564.407287
1,3b697a20d9e427646d92567910af6d57,2016-10-03 09:44:50,3.000000,19.924525,23.178738,3ae08df6bcbfe23586dd431c40bddbb7,29.90,15.56,300.0,16.0,16.0,16.0,85801,85801,4106,4106,709.921605
2,be5bc2f0da14d8071e2d45451ad119d9,2016-10-03 16:56:50,6.073519,21.094375,24.057500,fd7fd78fd3cbc1b0a6370a7909c0a629,21.90,17.19,400.0,16.0,16.0,16.0,15802,15802,98280,98280,914.131568
3,a41c8759fbe7aab36ea07e038b2d4465,2016-10-03 21:13:36,8.958426,29.323819,30.572581,b72b39418216e944bb34e35f4d3ea8c7,36.49,17.24,767.0,26.0,8.0,20.0,18015,18015,90040,90040,816.498486
4,d207cc272675637bfed0062edffd0818,2016-10-03 22:06:03,9.863947,27.027488,27.542813,107177bf61755f05c604fe57e02467d6,119.90,13.56,2050.0,40.0,11.0,34.0,14940,14940,13185,13185,212.084845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99697,52018484704db3661b98ce838612b507,2018-08-29 12:25:59,1.382257,1.425810,1.432269,777798445efd625458a90c13f3b3e6e7,63.90,9.20,1500.0,28.0,22.0,18.0,5125,5125,5863,5863,18.854775
99698,0b223d92c27432930dfe407c6aea3041,2018-08-29 14:18:23,1.038831,1.079028,1.087870,2b4472df15512a2825ae86fd9ae79335,209.00,46.48,13550.0,48.0,49.0,49.0,82400,82400,80045,80045,10.343719
99699,168626408cb32af0ffaf76711caae1dc,2018-08-29 14:18:28,0.917720,1.098704,1.106979,bdcf6a834e8faa30dac3886c7a58e92e,45.90,15.39,1614.0,31.0,16.0,28.0,30111,30111,38600,38600,431.976676
99700,03ef5dedbe7492bdae72eec50764c43f,2018-08-29 14:52:00,0.858322,1.063623,1.072905,c7f27c5bef2338541c772b5776403e6a,24.90,8.33,450.0,28.0,9.0,19.0,1320,1320,9541,9541,10.312870
99701,35a972d7f8436f405b56e36add1a7140,2018-08-29 15:00:37,0.976806,1.050810,1.057627,d04857e7b4b708ee8b8b9921163edba3,84.99,8.76,450.0,16.0,4.0,20.0,4102,4102,13483,13483,140.915746

In [262]:
df_final = df_final.drop(columns=["product_id", "geolocation_zip_code_prefix_x", "geolocation_zip_code_prefix_y"])
df_final

,order_id,order_purchase_timestamp,time_to_delivery_from_shipment,time_to_delivery_from_order_approved,time_to_delivery_from_order_purchased,price,freight_value,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,customer_zip_code_prefix,shipment_distance
0,bfbd0f9bdef84302105ad712db648a6c,2016-09-15 12:16:38,1.608160,54.813194,54.813194,44.99,2.83,1000.0,16.0,16.0,16.0,81810,14600,564.407287
1,3b697a20d9e427646d92567910af6d57,2016-10-03 09:44:50,3.000000,19.924525,23.178738,29.90,15.56,300.0,16.0,16.0,16.0,85801,4106,709.921605
2,be5bc2f0da14d8071e2d45451ad119d9,2016-10-03 16:56:50,6.073519,21.094375,24.057500,21.90,17.19,400.0,16.0,16.0,16.0,15802,98280,914.131568
3,a41c8759fbe7aab36ea07e038b2d4465,2016-10-03 21:13:36,8.958426,29.323819,30.572581,36.49,17.24,767.0,26.0,8.0,20.0,18015,90040,816.498486
4,d207cc272675637bfed0062edffd0818,2016-10-03 22:06:03,9.863947,27.027488,27.542813,119.90,13.56,2050.0,40.0,11.0,34.0,14940,13185,212.084845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99697,52018484704db3661b98ce838612b507,2018-08-29 12:25:59,1.382257,1.425810,1.432269,63.90,9.20,1500.0,28.0,22.0,18.0,5125,5863,18.854775
99698,0b223d92c27432930dfe407c6aea3041,2018-08-29 14:18:23,1.038831,1.079028,1.087870,209.00,46.48,13550.0,48.0,49.0,49.0,82400,80045,10.343719
99699,168626408cb32af0ffaf76711caae1dc,2018-08-29 14:18:28,0.917720,1.098704,1.106979,45.90,15.39,1614.0,31.0,16.0,28.0,30111,38600,431.976676
99700,03ef5dedbe7492bdae72eec50764c43f,2018-08-29 14:52:00,0.858322,1.063623,1.072905,24.90,8.33,450.0,28.0,9.0,19.0,1320,9541,10.312870
99701,35a972d7f8436f405b56e36add1a7140,2018-08-29 15:00:37,0.976806,1.050810,1.057627,84.99,8.76,450.0,16.0,4.0,20.0,4102,13483,140.915746

In [264]:
df_final.to_csv("./dataset.csv", index=False)